language: python
python:
    - "3.4"
    - "3.5"
before_install:
    - wget https://github.com/samtools/samtools/releases/download/1.3/samtools-1.3.tar.bz2 -O - | tar xj
    - cd samtools-1.3 ; make ; sudo make install ; cd ..
install:
    - pip install pysam
    - pip install coveralls
    - pip install pytest
script:
    - coverage run --source=MrBam -m pytest
after_success:
    - coveralls
